action_id: trunk-share-with-everyone
date: 2023-11-06 21:34:25
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1699306465
full_timestamp:
  nanos: 534777000
  seconds: 1699306465
trunk_version: 1.17.1
